name: mmoQuest
version: ${releaseVersion} b${buildNumber}
description: Open-ended questing with any type of quest or reward.
author: mmoMinecraftDev
website: http://mmo.me.uk

main: mmo.Quest.MMOQuest
depend: [Spout, mmoCore]
